FROM ubuntu:16.04

# -- MAINTAINER Jan Suchotzki <jan@suchotzki.de>

# first create user and group for all the X Window stuff
# required to do this first so have consistent uid/gid between server and client container
RUN addgroup --system xusers \
  && echo "root:thing99" | chpasswd \
  && adduser \
			--home /home/xuser \
			--disabled-password \
			--shell /bin/bash \
			--gecos "user for running X Window stuff" \
			--ingroup xusers \
			--quiet \
			xuser

# Install xvfb as X-Server and x11vnc as VNC-Server
RUN apt-get update && apt-get install -y --no-install-recommends \
				xvfb \
				xauth \
				x11vnc \
				x11-apps \
				x11-utils \
				x11-xserver-utils \
                                xterm \
                                fvwm \
                                xfonts-base

# create or use the volume depending on how container is run
# ensure that server and client can access the cookie
RUN mkdir -p /Xauthority && chown -R xuser:xusers /Xauthority
VOLUME /Xauthority

# start x11vnc and expose its port
ENV DISPLAY :0.0
EXPOSE 5900
COPY docker-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# ----

RUN apt update \
 && apt-get -y  install sudo wget apt-transport-https vim \
 && apt-get -y install git g++ make python-dev help2man unixodbc libfuse-dev \
    libcurl4-gnutls-dev libbz2-dev zlib1g-dev libpam0g-dev libssl-dev \
    libxml2-dev libkrb5-dev unixodbc-dev libjson-perl python-psutil \
    python-jsonschema super python-exif odbc-postgresql 

ADD db_commands.txt /

RUN apt-get -y  install sudo wget apt-transport-https vim postgresql \
 && su - postgres -c 'psql -f /db_commands.txt' \

RUN rm -rf /var/lib/apt/lists/*
    
# switch to user and start
USER xuser

CMD ["/entrypoint.sh"]
